name: Karate Tests Pipeline

on:
  push:
    branches: [ "Envio-SMS-karate" ]
  workflow_dispatch:
    inputs:
      karate_tag:
        description: 'Tag que deseas ejecutar individualmente'
        required: true
        default: '@componenteSMS'

jobs:
  karate-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Ejecutar Pruebas Karate
        run: |
          TAG_TO_RUN="${{ inputs.karate_tag }}"
          if [ -z "$TAG_TO_RUN" ]; then
            TAG_TO_RUN="@componenteSMS"
          fi

          mvn clean verify \
            -Dkarate.env=dev \
            -Dkarate.options="--tags $TAG_TO_RUN" \
            -Dclient-Id="${{ secrets.CLIENT_ID }}" \
            -Dclient-Secret="${{ secrets.CLIENT_SECRET }}" \
            -Drefresh-Token="${{ secrets.REFRESH_TOKEN }}"