name: Karate API Tests

on:
  push:
    branches:
      - Envio-SMS-karate
  pull_request:
    branches:
      - Envio-SMS-karate
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run Karate tests
        run: |
          mvn clean verify \
            -Dkarate.env=dev \
            -Dkarate.options="--tags=@componenteSMS" \
            -Dclient-Id="${{ secrets.CLIENT_ID }}" \
            -Dclient-Secret="${{ secrets.CLIENT_SECRET }}" \
            -Drefresh-Token="${{ secrets.REFRESH_TOKEN }}"